# Generated by Django 4.1.7 on 2023-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
