# Generated by Django 4.1.7 on 2023-04-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_articles_image_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='ArticlesImage',
        ),
    ]
