# Generated by Django 4.1.7 on 2023-04-19 18:31

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_postimage_articlesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
        ),
        migrations.AlterField(
            model_name='articlesimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
