# Generated by Django 4.1.7 on 2023-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cartorder_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product1',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='product1',
            field=models.ManyToManyField(blank=True, null=True, related_name='product1', to='cart.cartitems'),
        ),
    ]
