# Generated by Django 4.1.7 on 2023-05-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_remove_cartorder_product_cartorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productt', to='cart.cartitems'),
        ),
    ]
