# Generated by Django 4.1.7 on 2023-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_remove_cartorder_product_cartorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='productt', to='cart.cartitems'),
        ),
    ]
