# Generated by Django 4.1.7 on 2023-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_remove_cartorder_product_cartorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product',
            field=models.ManyToManyField(null=True, to='cart.cartitems'),
        ),
    ]
