# Generated by Django 4.1.7 on 2023-05-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_alter_cartorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='cart.cart'),
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='product',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='cart.cartitems'),
        ),
    ]
