# Generated by Django 4.1.7 on 2023-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_cartorder_owner_remove_cartorder_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='owner',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='owner',
            field=models.ManyToManyField(related_name='purchase', to='cart.cart'),
        ),
    ]
