# Generated by Django 4.1.7 on 2023-06-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_alter_cartitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
